# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fee0be5f6fa8a0e10d676a0aa72e2dc37aaf327ee85fa0e4475d9fdea5aa93819e24cb503833139ad3531ec76dc7ea061f578656889365c4b195ff65751816b0

test:
  secret_key_base: 0e08b6b548a634b8a224e0c82d5bfe15362c0bc18d66552021e511d4b7fa0b882af842bdb792da20816a35206859397505b184ff1e36ad9653e12f8000d6c06e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
